spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: zan384380
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myBi

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000